CC=rosrun ed_perception ed-learning-tool ~/.ed/learning ~/ros/hydro/system/src/ed_object_models/configs/model_lists/all_models.yml ~/ros/hydro/system/src/ed_object_models/models ~/ros/hydro/system/src/ed_object_models/configs/odu_finder/

~/learning_tool_output/odu_finder/database/images.documents:all_models.yml ~/ros/hydro/dev/src/ed/config/config_amigo.yml
	$(CC)