CC=rosrun ed_perception ed-learning-tool ~/.ed/learning ~/learning_tool_output/models/ ~/learning_tool_output/odu_finder/

~/learning_tool_output/odu_finder/database/images.documents:all_models.yml
	$(CC)



