#! /usr/bin/python

import tue_config
import sys

if __name__ == "__main__":

    if len(sys.argv) < 2:
        print "Please specify a configuration file (.py, .yaml or .json)"
        sys.exit(1)

    cfg = tue_config.from_file(sys.argv[1], relative=False)
    tue_config.write_yaml(cfg)
