obstacle_range: 8.0
raytrace_range: 10.0
#inflation_radius: 0.2
map_topic:  /map # /ed/navigation/map #
global_frame: /map
robot_base_frame: /load/base_link
update_frequency: 5.0
publish_frequency: 5.0
static_map: false
rolling_window: true
width: 16.0
height: 16.0
resolution: 0.05
inflation_radius: 0.2 

observation_sources: laser_scan_sensor
laser_scan_sensor: { sensor_frame: /ropod/laser/scan, data_type: LaserScan, topic: /ropod/laser/scan, marking: true, clearing: true , inf_is_valid: true, observation_persistence: 0.0 }

#plugins:
    #- {name: ed_occupancy_grid,                 type: "costmap_2d::StaticLayer"}    
    #- {name: configuration_space,               type: "costmap_2d::InflationLayer"}
    #- {name: recent_obstacles,                  type: "costmap_2d::ObstacleLayer"}
    #### - {name: robot_footprint,                   type: "costmap_2d::FootprintLayer"}


##### LAYER CONFIGURATION

#ed_occupancy_grid:
    #map_topic: /ed/navigation/map # /map #
    #track_unknown_space: true
    #use_maximum: true
    #lethal_cost_threshold: 99

### Workspace to configuration space
#configuration_space:
    #use_footprint: true
    #target_cell_value: 254
    #dilation_cell_value: 253
    #dilation_radius: 0.35 # inscribed radius
    #inflation_radius: 0.2 # optimization
    #cost_scaling_factor: 3.0
#recent_obstacles:
    #observation_sources: laser_scan_sensor
    #laser_scan_sensor: { sensor_frame: /ropod/laser/scan, data_type: LaserScan, topic: /ropod/laser/scan, marking: true, clearing: true , inf_is_valid: true, observation_persistence: 0.0 }
