world:
- type: robot-lab
  pose: { x: 0, y: 0, z: 0 }

plugins:
  - name: gui_server
    lib: libed_gui_server_plugin.so

  - name: tf_publisher
    lib: libed_tf_publisher_plugin.so
    parameters:
      root_frame_id: /map
      exclude: optional_ids_to_exclude
