world:
- type: robot-lab
  pose: { x: 0, y: 0, z: 0 }

plugins:
- name: gui_server
  lib: libed_gui_server_plugin.so
- name: localization
  lib: libed_localization_plugin.so
  parameters:
    robot_name: amigo
    initial_pose_topic: /amigo/initialpose
    num_particles: 500
    initial_pose:
        x: 0.586 #$(env ROBOT_INIT_X)
        y: 4.259 #$(env ROBOT_INIT_Y)
        rz: 0 #$(env ROBOT_INIT_PHI)
    laser_model:
        topic: /amigo/base_laser/scan
        num_beams: 100
        z_hit: 0.95
        sigma_hit: 0.2
        z_short: 0.1
        z_max: 0.05
        z_rand: 0.05
        lambda_short: 0.1
        range_max: 10
        min_particle_distance: 0.01
        min_particle_rotation_distance: 0.02
    odom_model:
        map_frame: map
        odom_frame: /amigo/odom
        base_link_frame: /amigo/base_link
        alpha1: 0.05   # rot -> trans + strafe
        alpha2: 0.5    # trans -> rot
        alpha3: 0.5    # trans -> trans
        alpha4: 0.5    # rot -> rot
        alpha5: 0.5    # trans -> strafeb: libed_gui_server_plugin.so
- name: navigation
  lib: libed_navigation_plugin.so
  parameters:
    occupancy_grid_publisher:
        resolution: 0.05
        frame_id: /map
        min_z: 0.025
        max_z: 1.8
        default_offset: 0.7
