world:
  - id: walls
    shape:
      heightmap:
        image: $(file heightmap.pgm)
        height: 2
        resolution: 0.025
        pose: { x: -10.0, y: -10.0, z: 0 }
  
plugins:
    - name: gui_server
      lib: libed_gui_server_plugin.so
