TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_vel_theta: 0.2
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  meter_scoring: true

  holonomic_robot: true
  
controller_frequency: 10.0
robot_base_frame: /pico/base_link
global_frame: /map  
