obstacle_range: 5.0
raytrace_range: 10.0
# footprint: [[-0.3, 0.3], [0.3, 0.3], [0.3, -0.3], [-0.3, -0.3]]
footprint: [[-0.1, 0.4], [1.4, 0.4], [1.4, -0.4], [-0.1, -0.4]]
# inflation_radius: 0.2
# robot_radius: 0.2


