models:
    - name: crowd
    - name: human
    - name: cup
    - name: beer
    - name: cola
    - name: chewing_gum_white
    - name: deodorant
    - name: sprite
    - name: coffee_pads
    - name: fanta
    - name: tea
