models:
    - name: human
    - name: beer
    - name: coke
    - name: fanta
    - name: ice_tea
    - name: tea
    - name: coffee_pads
    - name: deodorant
    - name: frutas
    - name: sprite
    - name: teddy