TrajectoryPlannerROS:
  max_vel_x: 0.45
  min_vel_x: 0.05
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  meter_scoring: true

  holonomic_robot: true
  
controller_frequency: 5.0
robot_base_frame: /pico/base_link
global_frame: /map  
pdist_scale: 3.0
occdist_scale: 2.0
