TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 0.7
  min_in_place_vel_theta: 0.3

  acc_lim_theta: 2.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  meter_scoring: true

  holonomic_robot: true
  controller_frequency: 5.0
  pdist_scale: 2.0
  occdist_scale: 0.02
  latch_xy_goal_tolerance: true
  clearing_rotation_allowed: false
  


robot_base_frame: /pico/base_link
global_frame: /map  

