plugins:
    # Obstacles
    - {name: ed_occupancy_grid,                 type: "costmap_2d::StaticLayer"}
    - {name: robot_footprint,                   type: "costmap_2d::FootprintLayer"}
    - {name: configuration_space,               type: "costmap_2d::InflationLayer"}

# Ed World model layer
ed_occupancy_grid:
    global_frame: /map
    map_topic: /ed/navigation/map
    track_unknown_space: false

# Workspace to configuration space
configuration_space:
    use_footprint: false
    target_cell_value: 254
    dilation_cell_value: 253
    dilation_radius: 0.37 # 2cm margin
    inflation_radius: 0.2

global_costmap:
  global_frame: /map
  map_topic: /ed/navigation/map
  robot_base_frame: /pico/base_link
  update_frequency: 2.0
  static_map: true
  track_unknown_space: false

