header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: 'map'
poses:
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: 3.92092418671
      y: 1.82455599308
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.482824507019
      w: 0.875717132082
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: 3.45166087151
      y: 0.0115420222282
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.748425392531
      w: 0.663218992351
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: 2.90270781517
      y: -5.31237697601
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.990889295005
      w: -0.134678896065
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: -2.90713310242
      y: -4.6593413353
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.927442676261
      w: 0.373965348997
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: -6.56064224243
      y: -3.86945700645
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.92775287068
      w: 0.37319513789
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: -7.87061166763
      y: -1.98190188408
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.00794839213885
      w: 0.999968411032
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: -4.72531557083
      y: -2.10887074471
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.99998963346
      w: 0.00455334736747
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: -6.76369524002
      y: -2.7368452549
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.703932348704
      w: 0.710267026159
