header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: 'map'
poses:
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: 4.57786273956
      y: -0.440911144018
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.597506056817
      w: 0.801864397556
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: 4.17903470993
      y: -7.28202915192
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.990114285985
      w: 0.14026296977
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: 1.91803765297
      y: -7.34335279465
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: 0.996258398396
      w: 0.0864245545264
  

