header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: 'PAUSE'
poses:
- header:
    seq: 0
    stamp:
      secs: 0
      nsecs: 0
    frame_id: 'map'
  pose: 
    position: 
      x: 4.57786273956
      y: -0.440911144018
      z: 0.0
    orientation: 
      x: 0.0
      y: 0.0
      z: -0.597506056817
      w: 0.801864397556
  

