- START:
    position: [0.65, 2.2, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
- MOBIDIK:
    position: [1.8, 2.2, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
- ELEVATOR:
    position: [2.6, 1.95, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
- INSIDE_ELEVATOR1:
    position: [2.9, 2.9, 0.0]
    orientation: [0.70711, 0.0, 0.0, 0.70711]
- INSIDE_ELEVATOR2:
    position: [2.9, 2.9, 0.0]
    orientation: [0.70711, 0.0, 0.0, -0.70711]
- OUTSIDE_ELEVATOR:
    position: [3.7, 2.3, 0.0]
    orientation: [1.0, 0.0, 0.0, 0.0]
