world_name: hospital_test_amcl
  
plugins:
  - name: gui_server
    lib: libed_gui_server_plugin.so     
  - name: navigation
    lib: libed_navigation_plugin.so
    parameters:
      occupancy_grid_publisher:
        resolution: 0.05       # Grid cell size in meters
        frame_id: /map         # Frame id of the occupancy grid
        min_z: 0.025           # All entities below min_z and above max_z are not
        max_z: 1.8             # Projected onto the occupancy grid
        default_offset: 0.7    # <-- not used for ROS' Move Base, but needs to be specified
        convex_hull_enabled: 1 # Enable projecting unmodeled entities into navigation map
  - name: laser_integration
    lib: libed_laser_plugin.so
    frequency: 10
    parameters:
        laser_topic: /ropod/laser/scan
        min_segment_size_pixels: 5
        world_association_distance: 0.1
        segment_depth_threshold: 0.2
        min_cluster_size: 0.05
        max_cluster_size: 10.0
        max_gap_size: 1
        check_door_status: 1
  - name: entity_clearer
    lib: libed_clearer_plugin.so
    enabled: 1
    parameters:
        entity_timeout: 1.0        
